#pragma once

#define UNICODE_SELECTED_MODES UC_WINC, UC_WIN, UC_LNX, UC_OSX
#define UNICODE_CYCLE_PERSIST false

#ifdef RGB_DI_PIN
    #undef RGBLIGHT_ANIMATIONS
    #define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_STATIC_LIGHT
#endif

// #undef RGB_BACKLIGHT_ALPHAS_MODS_ROW_0
// #define RGB_BACKLIGHT_ALPHAS_MODS_ROW_0 0b0100000000000001